### ISSUE TITLE
Add ERC20 compatibility

### ISSUE THREAD

**Issue by timogilvie** [Stakedllc/eth-casper-pool#1]
Add the functionality necessary to create a token and follow the ERC-20 standard.  (Just putting this down to recap our conversation and track the issue). 

NAME: Staked - Ethereum Staking Contract for Casper Staking

Is this consistent with how other tokens are named?

**Comment by johhonn** [comment]
I called it StakeToken but that's fine. I finished writing the contracts
today. We could talk tomorrow and discuss the functionality you want.

**Comment by timogilvie** [comment]
Tomorrow is great. Can you talk at 9:30am?

**Comment by johhonn** [comment]
Thats works for me.

**Comment by timogilvie** [comment]
ok - great. Please check in code and call me at 646 334 3372.
